### ISSUE TITLE
How to make UI Perfom?

### ISSUE THREAD

**Issue by dytlgozj** [dytlgozj/WebtoonAlarm#10]
우선 UI의 설계도
구체적으로는 버튼이 어디에 어떻게 몇개 달릴것인지 같은것에 대하여 생각하는 것이 좋을것 같은데
어떻게 생각해?
시간은 일단 마일스톤에 적혀있듯이 1주일동안으로 설정해놓았어.

**Comment by Libria** [comment]
<img width="81" alt="default" src="https://cloud.githubusercontent.com/assets/22048634/20208770/a9465a92-a833-11e6-88a2-10a3d2c967b0.PNG">
대충 요렇게 해다가 메인 화면에 웹툰 구성넣고
저기 쩜세개 옵션으로 만들어서 웹툰 지정하면 될듯

**Comment by Libria** [comment]
UI 그냥 안드로이드 스튜디오에서 제공하는 기본 세팅으로 하다가 나중에 익숙해지면 갈아버리자.

**Comment by dytlgozj** [comment]
it's solved.
