### ISSUE TITLE
Why there is a "9999"?

### ISSUE THREAD

**Issue by dytlgozj** [dytlgozj/WebtoonAlarm#50]
전달받은 값은 9999

이거 뭐하러 있는거야? 알림은 제대로 동작하는 것 같은데
뭘 테스트하기 위해 전달받은값을 띄우는 거야?

**Comment by Libria** [comment]
아 저거 원래 notification 레이아웃을 만들어서 거기로 이동되게 설계되있었는데
그럴 필요가 없어서 바로 MainActivity로 오도록 걸어버렸어..
notification 레이아웃을 안불러주면 오류발생으로 프로그램이 안돌아가서 
삭제가 안됬을 뿐임
